language: node_js

cache: npm

node_js:
- '8'

sudo: false

script:

after_script:

deploy:
- provider: npm
  email: 'devmonk@mediamonks.com'
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: '8'
  skip_cleanup: true
